// EuroPrix — mocked product data (demo, plausible figures)
window.EUROPRIX_DATA = {
  featured: {
    id: "airpods-pro-2",
    brand: "Apple",
    title: "AirPods Pro (2ᵉ génération) — USB-C",
    bestCountry: "DE",
    prices: {
      FR: 279.00,
      DE: 219.90,
      ES: 239.00,
    },
    updatedMinutesAgo: 14,
  },

  catalogue: [
    {
      id: "iphone-15-pro",
      brand: "Apple",
      title: "iPhone 15 Pro 256 Go — Titane naturel",
      prices: { FR: 1329, DE: 1199, ES: 1259 },
      bestCountry: "DE",
      updated: "il y a 38 min",
      placeholder: "Photo iPhone 15 Pro",
    },
    {
      id: "sony-xm5",
      brand: "Sony",
      title: "WH-1000XM5 — Casque réduction de bruit",
      prices: { FR: 379, DE: 299, ES: 329 },
      bestCountry: "DE",
      updated: "il y a 2 h",
      placeholder: "Photo Sony XM5",
    },
    {
      id: "macbook-air-m3",
      brand: "Apple",
      title: "MacBook Air 13\" M3 — 16 Go / 512 Go",
      prices: { FR: 1599, DE: 1499, ES: 1529 },
      bestCountry: "DE",
      updated: "il y a 9 min",
      placeholder: "Photo MacBook Air M3",
    },
    {
      id: "kindle-pw",
      brand: "Amazon",
      title: "Kindle Paperwhite 16 Go — Signature",
      prices: { FR: 199.99, DE: 169.99, ES: 179.99 },
      bestCountry: "DE",
      updated: "il y a 1 h",
      placeholder: "Photo Kindle Paperwhite",
    },
    {
      id: "switch-oled",
      brand: "Nintendo",
      title: "Switch OLED — Édition Mario rouge",
      prices: { FR: 349, DE: 299, ES: 319 },
      bestCountry: "DE",
      updated: "il y a 4 h",
      placeholder: "Photo Switch OLED",
    },
    {
      id: "dyson-v15",
      brand: "Dyson",
      title: "V15 Detect Absolute — Aspirateur sans fil",
      prices: { FR: 799, DE: 649, ES: 729 },
      bestCountry: "DE",
      updated: "il y a 27 min",
      placeholder: "Photo Dyson V15",
    },
    {
      id: "ipad-air",
      brand: "Apple",
      title: "iPad Air 11\" M2 — 256 Go Wi-Fi",
      prices: { FR: 949, DE: 879, ES: 909 },
      bestCountry: "DE",
      updated: "il y a 12 min",
      placeholder: "Photo iPad Air M2",
    },
    {
      id: "lego-millennium",
      brand: "LEGO",
      title: "Star Wars Faucon Millenium UCS",
      prices: { FR: 849, DE: 699, ES: 749 },
      bestCountry: "DE",
      updated: "il y a 3 h",
      placeholder: "Photo LEGO Millenium",
    },
    {
      id: "ps5-slim",
      brand: "Sony",
      title: "PlayStation 5 Slim — Édition Disque",
      prices: { FR: 549, DE: 499, ES: 519 },
      bestCountry: "DE",
      updated: "il y a 51 min",
      placeholder: "Photo PS5 Slim",
    },
    {
      id: "instax-mini",
      brand: "Fujifilm",
      title: "Instax Mini 12 — Pack appareil + 60 films",
      prices: { FR: 119, DE: 89, ES: 99 },
      bestCountry: "DE",
      updated: "il y a 18 min",
      placeholder: "Photo Instax Mini 12",
    },
    {
      id: "bose-soundlink",
      brand: "Bose",
      title: "SoundLink Flex — Enceinte Bluetooth",
      prices: { FR: 179, DE: 139, ES: 159 },
      bestCountry: "DE",
      updated: "il y a 1 h",
      placeholder: "Photo Bose SoundLink Flex",
    },
    {
      id: "samsung-s24",
      brand: "Samsung",
      title: "Galaxy S24 Ultra 512 Go — Titane noir",
      prices: { FR: 1469, DE: 1299, ES: 1399 },
      bestCountry: "DE",
      updated: "il y a 22 min",
      placeholder: "Photo Galaxy S24 Ultra",
    },
  ],
};
